<?php

	session_start();
	require_once("bdconnect.php");
	require('UserInfo.php');
	require_once 'fpdf/fpdf.php';
	if(isset($_SESSION['admin_id'])){
		if(isset($_SESSION['search_name']) && isset($_SESSION['search_month']) && isset($_SESSION['search_year'])){
			$get_serch_name = $_SESSION['search_name'];
			$get_serch_month = $_SESSION['search_month'];
			$get_serch_year = $_SESSION['search_year'];
			$get_admin_name = $_SESSION['admin_name'];

			switch ($get_serch_month) {
			  case "01":
				$show_month = "January";
				break;
			  case "02":
				$show_month = "February";
				break;
			  case "03":
				$show_month = "March";
				break;
			  case "04":
				$show_month = "April";
				break;
			  case "05":
				$show_month = "May";
				break;
			  case "06":
				$show_month = "June";
				break;
			  case "07":
				$show_month = "July";
				break;
			  case "08":
				$show_month = "August";
				break;
			  case "09":
				$show_month = "September";
				break;
			  case "10":
				$show_month = "October";
				break;
			  case "11":
				$show_month = "November";
				break;
			  case "12":
				$show_month = "December";
				break;
			  default:
				$show_month = "Select Month!!!";   
			}

			date_default_timezone_set('Asia/Dhaka');
			// Date
			$download_date = date('d/m/Y');
			// Time
			$download_time = date('h:ia');
			
			$pdf = new FPDF();
			$pdf->AddPage();
			
			// Header
			$pdf->SetFont("Arial","B",28);
			$pdf->Image('logo.png',10,14,55);
			$pdf->Cell(48,10,"",0,0,"");
			$pdf->Cell(100,12,"Agata Feed Mills Ltd.",0,1,"");
			$pdf->SetFont("Times","",10);
			$pdf->Cell(48,0,"",0,0,"");
			$pdf->Cell(100,5,"Head Office: Rupayan Trade Center, (15th floor)114, kazi Nazrul",0,1,"");
			$pdf->Cell(48,0,"",0,0,"");
			$pdf->Cell(100,5,"Islam Avenue, Banglamotor, Dhaka-1000, Bangladesh.",0,1,"");
			$pdf->Cell(48,0,"",0,0,"");
			$pdf->Cell(100,5,"Factory: Korpai, upazila-burichang, Comilla, Bangladesh.",0,1,"");
			$pdf->Line(10,40,200,40);
			$pdf->Cell(0,8,"",0,1,"");
			
			// Report Name
			$pdf->SetFont("Arial","B",12);
			$pdf->Cell(190,8,"Attendance Report",1,1,"C");
			$pdf->Cell(0,2,"",0,1,"");
			
			//Name
			$pdf->SetFont("Arial","",12);
			$pdf->Cell(20,8,"Name: ",0,0,"R");
			$pdf->Cell(50,8,$get_serch_name,0,0,"L");
			// Month
			$pdf->Cell(6,8,"",0,0,"");
			$pdf->Cell(21,8,"Month: ",0,0,"R");
			$pdf->Cell(30,8,$show_month,0,0,"L");
			// Year
			$pdf->Cell(20,8,"",0,0,"");
			$pdf->Cell(20,8,"Year: ",0,0,"R");
			$pdf->Cell(30,8,$get_serch_year,0,1,"L");
			$pdf->Cell(0,2,"",0,1,"");
			
			
			// Get Default ip
			$get_default_IP = "select * from user_account where name='$get_serch_name'";
			$get_default_IP_result = mysqli_query($connect,$get_default_IP);
			while($row = mysqli_fetch_assoc($get_default_IP_result)){
				$get_user_default_ip = $row['ip'];
			}
			// Table
			$pdf->SetFont("Arial","",11);
			$pdf->Cell(30,6,"Date",1,0,"C");
			$pdf->Cell(30,6,"Status",1,0,"C");
			$pdf->Cell(20,6,"Time",1,0,"C");
			$pdf->Cell(40,6,"IP ($get_user_default_ip)",1,0,"C");
			$pdf->Cell(30,6,"Device",1,0,"C");
			$pdf->Cell(40,6,"Opareting System",1,1,"C");
			
			$report_query = "select * from attendance_report where name='$get_serch_name' && month='$get_serch_month' && year='$get_serch_year'";
			$report_result = mysqli_query($connect,$report_query);
			while($row = mysqli_fetch_assoc($report_result)){
				$pdf->SetFont("Arial","",11);
				$pdf->Cell(30,6,$row['date'],1,0,"C");
				$pdf->Cell(30,6,$row['status'],1,0,"C");
				$pdf->Cell(20,6,$row['time'],1,0,"C");
				$pdf->Cell(40,6,$row['ip'],1,0,"C");
				$pdf->Cell(30,6,$row['device'],1,0,"C");
				$pdf->Cell(40,6,$row['os'],1,1,"C");
			}
			
			//Generated By
			$pdf->SetFont("Arial","",7);
			$pdf->Cell(180,1,"",0,1,"");
			$pdf->Cell(58,5,"This report is generated by redcellsbd.com/agata",0,0,"");
			// Downloaded By
			$pdf->Cell(1,5,"",0,0,"");
			$pdf->Cell(20,5,"Downloaded By: ",0,0,"R");
			$pdf->Cell(25,5,$get_admin_name,0,0,"L");
			// Download Date
			$pdf->Cell(1,5,"",0,0,"");
			$pdf->Cell(10,5,"Date: ",0,0,"R");
			$pdf->Cell(15,5,$download_date,0,0,"L");
			// Download Time
			$pdf->Cell(1,5,"",0,0,"");
			$pdf->Cell(8,5,"Time: ",0,0,"R");
			$pdf->Cell(12,5,$download_time,0,0,"");
			// Powered By
			$pdf->Cell(1,5,"",0,0,"");
			$pdf->Cell(18,5,"Powered By: ",0,0,"R");
			$pdf->Cell(18,5,"Avijit Datta",0,1,"L");
		
			$pdf->Output();
		}
	} else {
		echo"<script>
				alert('Enter All Input. Please try again..!');
				window.location = 'search_data.php';
			</script>";
			}
?>